### PR TITLE
feat: Replace MessageBoxW invocation with Tauri dialog

### PR DESCRIPTION
**Pull request by Jan200101**
With Tauri 2.0 this will require a plugin

### CODE REVIEW

**Comment by Jan200101** [comment]
Copied the textbox code into `linux_checks` for testing

Here it is on Linux:
image

Will test on Windows later

**Comment by Jan200101** [comment]
Tested on Windows using the same method as before

image

Pressing Ok opens the link, closing the window just closes it.

**Comment by Jan200101** [comment]
Its worth noting that this is non blocking and idk if this will cause problems when the main window wants to exit

**Comment by GeckoEidechse** [comment]
> It's worth noting that this is non blocking and idk if this will cause problems when the main window wants to exit

Don't have access to a Windows machine rn, you should be able to test that by just uninstalling WebView2 and then trying to run FlightCore and check if the behaviour is the same as before ^^

**Comment by Jan200101** [comment]
Tested and it did indeed break.

The blocking version does the job though.
image

**Review by GeckoEidechse — APPROVED** [review]
Works as expected in testing on Windows with WebView2 not installed:

image

**Pull request merged**
