### PR TITLE
i18n: Translations update from Weblate

### PR DESCRIPTION
**Pull request by harmony-weblate**
Translations update from [Weblate](https://translate.harmony.tf) for [Northstar/FlightCore](https://translate.harmony.tf/projects/northstar/flightcore/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by p0358** [comment]
Actually I only corrected two strings on translations made by someone else xd

**Comment by GeckoEidechse** [comment]
Oh, it's two commits, lol. I assume the translations are fine?

**Comment by p0358** [comment]
Yeah, except I have a serious doubt about `"date_prefix": "na"`

You should really make use of that screenshots function, because it's impossible to know what's the right translation for many of these things without seeing where they're actually used (and that's obvious only to the developers of the actual software, but translators can have no clue)

So I'm almost sure that one particular translation will be wrong, but correct one depends on where and how it's used...

**Comment by GeckoEidechse** [comment]
Aighty, I'll still merge then ig cause reverting translations is a bit of a hassle x_x

I'd love to add screenshots to weblate but I got other stuff to work on that's a bit more pressing. Made an issue in via #340 so if anyone wants to help out, get in touch and we'll set up perms or sth ig.

**Pull request merged**
