### PR TITLE
feat: Show warning banner on DevView

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Rendered:

image

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Doesn't look the prettiest, I'm happy to take any suggestion @Alystrasz :>

**Review by Alystrasz — CHANGES_REQUESTED** [review]
Red is for errors, you should use some orange :)
And add the warning icon: https://element-plus.org/en-US/component/alert.html#with-icon-and-description

**Comment by GeckoEidechse** [comment]
> Red is for errors, you should use some orange :) 

Tried orange first but it just blends with the background, making it look like an info box, not a warning ^^"

**Comment by Alystrasz** [comment]
Use a brighter orange then 😄

**Comment by GeckoEidechse** [comment]
Updated based on suggestion

Rendered:
image

**Review by Alystrasz — APPROVED** [review]
Confirmed working on Linux.

**Pull request merged**
