### PR TITLE
chore: Update tauri-plugin-store

### PR DESCRIPTION
**Pull request by Jan200101**
uses the dependency declaration recommended by upstream and lets us get rid of ugly build errors

image

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Didn't know they finally had a release, thanks :D

Do we also need to update the `package.json` for it as well?

https://github.com/R2NorthstarTools/FlightCore/blob/7ab55d005aa7661d1eed6cb0a77ee6b269bfdf91/src-vue/package.json#L15

**Comment by Jan200101** [comment]
> Didn't know they finally had a release, thanks :D

They don't
and they don't appear to be versioning the v1 version at all
but I don't want to look at that stupid error anymore and the v1 release appears to be left as is with only fixes no new features or changes.

> Do we also need to update the package.json for it as well?

fuck
give me a moment

**Comment by Jan200101** [comment]
okay, bumped the js package and made it follow the v1 release
On that note, the JS dependency was hardcoded to https://github.com/tauri-apps/tauri-plugin-store/commit/9bd993aa67766596638bbfd91e79a1bf8f632014 a 2022 commit
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
this also bumps the nodejs requirement to 14.6 but completely drops tslib

**Review by GeckoEidechse — APPROVED** [review]
Confirmed working in testing on Windows by changing language and restarting the application to see if the change persists.

**Pull request merged**
