### PR TITLE
feat: Start Northstar properly detached

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Simply run cmd with `start "" "PATH/TO/NORTHSTAR_EXE"`

### CODE REVIEW

**Comment by Alystrasz** [comment]
Closes #20.
Can you provide a test case which highlights this feature?

**Comment by Alystrasz** [comment]
On Windows 10 with `main`, no console appears at all; is it a big deal? Does it only appear with release builds?
On the other hand, I confirm using this branch properly shows content in a console window.

**Comment by GeckoEidechse** [comment]
> On Windows 10 with `main`, no console appears at all; is it a big deal? Does it only appear with release builds? On the other hand, I confirm using this branch properly shows content in a console window.

If you launch debug build of current `main` (without this PR) from console (i.e. by running `npx tauri dev`) that's expected cause then that console window acts as your console. If you launch it from a release build it will show the empty console.

In contrast this branch should always spawn Northstar + Northstar console window, regardless of debug or release builds ^^

**Review by Alystrasz — APPROVED** [review]
Confirmed working on Windows 10.

**Pull request merged**
