### PR TITLE
feat: Update to new wallpaper

### PR DESCRIPTION
**Pull request by GeckoEidechse**
I'm thinking if I already bump FlightCore version to 2.0 for `packages` support, why not also update the wallpaper for a change? :>

image

<details>
<summary>Old image</summary>

image

</details>

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Draft for now so it doesn't accidentally get merged until everything else is ready ^^

**Comment by GeckoEidechse** [comment]
@Alystrasz thoughts on the wallpaper? 👀

**Comment by Alystrasz** [comment]
Not so sure about that wallpaper 😁 

* Style of the image is not unified, *e.g.* I think the Northstar 3D model pops out too much regarding the background;
* There shouldn't be any image elements under the menu bar area, the image part there should be as uniform as possible to ease reading menu items.

I suggest looking into the numerous Titanfall concept arts 😃

**Comment by GeckoEidechse** [comment]
> * There shouldn't be any image elements under the menu bar area, the image part there should be as uniform as possible to ease reading menu items.

Agreed. I might be able to tweak the image a bit

> I suggest looking into the numerous Titanfall concept arts :smiley:

Ye, I primarily was thinking something Northstar related and something where the image isn't super noisy. For example I was considering using the one from Northstar



but decided against it due to it just being too "noisy" ^^

**Comment by Jan200101** [comment]
I agree that the above image is too noisy, there is way too much things that draw your attention away.

At the same time, the proposed image feels empty with the FlightCore pose and absolutely nothing else.

Maybe some minor effects should be re-added, like the rocket thrusters and the lens flare.

**Comment by GeckoEidechse** [comment]
I updated it :)

image

**Review by Jan200101 — APPROVED** [review]
I like it :+1:

**Review by Alystrasz — APPROVED** [review]
Submenus are still readably, it's a yes from me.

image

**Comment by Alystrasz** [comment]
@GeckoEidechse maybe add the image credits in the About section :)

**Comment by GeckoEidechse** [comment]
> @GeckoEidechse maybe add the image credits in the About section :)

Do I need to if the image is my own? ^^"

**Comment by Alystrasz** [comment]
> > @GeckoEidechse maybe add the image credits in the About section :)
> 
> Do I need to if the image is my own? ^^"

Let's say we'll be fine!

**Pull request merged**
