### PR TITLE
docs: Mention ways of reaching out

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Just mention some way how to ask for help when trying to contribute.

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
@Alystrasz should I add you as a point of contact as well? ^^

**Comment by Alystrasz** [comment]
Yep you can :)

**Comment by GeckoEidechse** [comment]
> Yep you can :)

Just add `@Akystrasz` or sth else?

**Comment by Alystrasz** [comment]
`@Alystrasz` is better 😄

**Pull request merged**
