### PR TITLE
feat: Add button to disable ModSettings mod

### PR DESCRIPTION
**Pull request by GeckoEidechse**
In preparation for Northstar releasing merged Mod Settings mod.

image

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
@EladNLG Hi :)

**Comment by EladNLG** [comment]
hello yes what do youk want

**Comment by catornot** [comment]
you should probably also add a button to disable all mods that depend on ModSettings.

**Comment by GeckoEidechse** [comment]
> you should probably also add a button to disable all mods that depend on ModSettings.

Do we need one? Cause AFAIK the merged code mirrors ModSettings functions so one can simply drop ModSettings mod, no?

**Comment by catornot** [comment]
> > you should probably also add a button to disable all mods that depend on ModSettings.
> 
> Do we need one? Cause AFAIK the merged code mirrors ModSettings functions so one can simply drop ModSettings mod, no?

I though it was different `¯\_(ツ)_/¯`

**Comment by ASpoonPlaysGames** [comment]
> Do we need one? Cause AFAIK the merged code mirrors ModSettings functions so one can simply drop ModSettings mod, no?

Not necessarily, there are two cases where they will break:

If a mod relies on pre 2.0 modsettings (should be very rare now, and not a lot we can do about it)

If a mod uses dependency constants. this will break the mod in some way, depends how it is made. Some mods will prompt the user to download modsettings, which is going to be confusing since it wont work

**Review by Alystrasz — APPROVED** [review]
Confirmed working on Windows.

**Pull request merged**
