### PR TITLE
fix: Pass launch options to Steam

### PR DESCRIPTION
**Pull request by Jan200101**
relying on a file to be parsed in time is unreliably, and if the file is open while we delete it we may run into locking problems downside is that this gives a fugly prompt

### CODE REVIEW

**Comment by Jan200101** [comment]
pretend I didn't forget to run clippy

**Comment by catornot** [comment]
> pretend I didn't forget to run clippy

you can configure rust-analyzer to use clippy instead of check

**Comment by Jan200101** [comment]
> you can configure rust-analyzer to use clippy instead of check

this would require me to even use rust-analyzer, I just wing it.

**Comment by Jan200101** [comment]
Tested this myself on Fedora 38

**Comment by GeckoEidechse** [comment]
So on my Steam install I cannot launch Northstar at all right now using `-northstar` at rn. No clue what's causing that. So I'm just gonna trust you and merge anyway ^^

**Pull request merged**
