### PR TITLE
fix: Stop opening PS to get Origin game path

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Now using a library instead of calling a PowerShell command should prevent the PowerShell window from opening.

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Supersedes #95

**Comment by Alystrasz** [comment]
How did you test this branch?

**Comment by GeckoEidechse** [comment]
> How did you test this branch?

On Windows I deleted saved path, commented out the [Steam game install path detection code](https://github.com/R2NorthstarTools/FlightCore/blob/2e47666762afc665d8f44e57c4f86ed72d9fcc13/src-tauri/src/lib.rs#L81-L98) so that it would only run the Origin detection and then I checked that it picks the Origin install.

To test the PowerShell window issue one needs to build the app (with updater disabled to prevent build failure due to missing keys), make sure that no persistent game install path is saved and then run it and see if the powershell window opens (haven't tested that part yet).

**Comment by GeckoEidechse** [comment]
> To test the PowerShell window issue one needs to build the app (with updater disabled to prevent build failure due to missing keys), make sure that no persistent game install path is saved and then run it and see if the powershell window opens (haven't tested that part yet).

Tested on my own machine now and got no PowerShell window pop-up.

**Review by Alystrasz — APPROVED** [review]
Shell doesn't show up with release build on Windows.

**Pull request merged**
