### PR TITLE
refactor: Replace all `println!()` with log statements

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Replace more `println!()` with calls to `log::info`, `log::warn`, etc

Continuation of
- #219
- #223

### CODE REVIEW

**Comment by catornot** [comment]
why so many commits?

**Review by Alystrasz — APPROVED** [review]
refactor: Replace all println with calls to logger

**Comment by GeckoEidechse** [comment]
> why so many commits?

I prefer doing smaller incremental changes and then validating those, so in this case replacing all calls in a function and then testing it to verify.
While a bit more tedious, it did help me find a bunch of smaller issues in the process ^^

Also, commit stats go brrrrr >:)

**Comment by catornot** [comment]
I just push to main

**Pull request merged**
